apiVersion: v1
kind: Service
metadata:
  name: {{ default "default-http-backend" .Values.defaultBackendName }}
  labels:
    app: {{ default "default-http-backend" .Values.defaultBackendName }}
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    tmp: {{ template "fullname" . }}
    provider: "devopskube"
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: {{ default "default-http-backend" .Values.defaultBackendName }}
